#!/bin/bash
# USAGE: $0 <arg1> <arg2>
# DESCRIPTION: This is a bar script
# ARGUMENTS:
#   <arg1> - The first argument
#   <arg2> - The second argument
# EXAMPLES:
#   foo.sh 1 2

echo 1

# Set to exit 1 to test comp scripts
# and assert they do not execute this script
# with the comp flag
exit 1
