#!/bin/bash
# USAGE: $0 <arg1> <arg2>
# DESCRIPTION: This is a foo script
# ARGUMENTS:
#   <arg1> - The first argument
#   <arg2> - The second argument
# EXAMPLES:
#   foo.sh 1 2
# TOME_COMPLETION

case $1 in
  --completion)
    echo -e "--help\\tHelp message for foo\\n"
    echo -e "--query\\tQuery message for foo\\n"
    echo -e "an-argument\\tArgument\\n"
    ;;
  *)
    echo 1
    ;;
esac
