name: ci

on:
  push:
    tags:
      - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: cashapp/activate-hermit@v1
        with:
          cache: "true"
      - name: Run go test
        run: make test-go
      - name: E2E test
        run: make test-e2e
  goreleaser:
    depends-on: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cashapp/activate-hermit@v1
        with:
          cache: "true"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  - uses: actions/checkout@v3
