name: Test
on:
  # # Indicates I want to run this workflow on all branches, PR, and tags
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: [ "main" ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup hermit
        run: source .hermit/bin/activate-hermit
      - name: Run go test
        run: make test-go
      - name: E2E test
        run: make test-e2e
