name: Release
on:
  # # Indicates I want to run this workflow on all branches, PR, and tags
  push:
    tags: ["v*"]
jobs:
  goreleaser:
    depends-on: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: cashapp/activate-hermit@v1
        with:
          cache: "true"
          working-directory: ".hermit"
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v3
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
